on:
  pull_request_target:
    types: [opened,synchronize]

name: OnSyncPR
jobs:
  check-format:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v2
        with:
          ref: develop
          fetch-depth: 0
      - name: Check for formatting changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: .github/check-format.sh
